INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Candied Papaya', 10.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Candied Mango', 10.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Assorted Dry Fruits', 11.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Bag of Cashews', 7.5, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Cooked Lentils', 5.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Cooked Hook Beans', 5.2, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Cooked Chickpeas', 6.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Steam Vegetables', 4.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Steam Greens', 4.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Mud Bean', 5.85, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Lentils from Salamanca', 3.3, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Garbanzos Chickpeas', 3.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Lex?²s Chickpeas', 4.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Hook Bean', 4.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Golden Bean', 6.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Sauco Chickpeas', 3.2, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Pardina Lentils', 2.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Red Beans', 3.7, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Black Eye Peas', 3.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('White Beans', 2.88, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Beige Beans', 2.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Peanuts', 0.8, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Peeled Pistachios', 2.2, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Marconas', 19.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Mix Nuts and Fruits', 1.2, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Tiger Nut', 9.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Black Plums', 12.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Mix Raisins', 13.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Red Plums', 13.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Raisins', 16.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Corinto Raisins', 8.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('White Raisin', 10.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Bag of Peanuts', 1.5, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Dried Chili Peppers', 2.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Chocolate Pieces', 10.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Chocolate Cover Peanuts', 12.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Carmel Chocolate Peanuts', 13.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Dried Pumpkin Seeds', 13.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Dried Mango', 14.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Dried Pineapple', 14.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Corn Kernels', 10.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Dried Figs', 8.5, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Mix Dried Fruits', 9.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Seafood Noodle Broth', 2.0, true);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Paella Broth', 2.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Meat Homestyle Broth', 2.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Fish Homestyle Broth', 2.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Vegetable Broth', 1.8, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Chicken Broth', 2.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Low Sodium Chicken Broth', 1.8, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Bowl Broth', 2.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Gourmet Chicken Broth', 3.0, false);
INSERT INTO items (display_name, unit_price, by_weight) VALUES ('Gazpacho Soup', 1.5, true);